AWSTemplateFormatVersion: 2010-09-09
Description: This template create NAT Gateway

Resources: 
  NatGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP.AllocationId
      SubnetId: !ImportValue PublicSubnetId
      Tags:
        - Key: Name
          Value: NAT Gateway

Outputs:
  NatGatewayId:
    Description: The NAT Gateway ID
    Value: !Ref NatGateway
    Export:
      Name: NatGatewayId